substitutions:
  bmp280_address: '0x76'
  temperature_offset: '0.0'
  humidity_offset: '0.0'
  pressure_offset: '0.0'
  altitude_m: '0.0'

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      id: air_temperature
      name: Temperature
      filters:
        - offset: ${temperature_offset}
    humidity:
      id: air_humidity
      name: Humidity
      filters:
        - offset: ${humidity_offset}
        - clamp:
            min_value: 0
            max_value: 100
    update_interval: 10s
  - platform: bmp280_i2c
    address: ${bmp280_address}
    pressure:
      id: station_pressure
      name: Station pressure
      filters:
        - offset: ${pressure_offset}
    update_interval: 10s
  - platform: copy
    source_id: station_pressure
    name: Sea level pressure
    filters:
      - lambda: return x / powf(1.0f - (${altitude_m} / 44330.0f), 5.255f);
