substitutions:
  bh1750_address: '0x23'
  light_transmission: '1.0'

sensor:
  - platform: bh1750
    address: ${bh1750_address}
    name: Illuminance
    update_interval: 10s
    filters:
      - lambda: return x / ${light_transmission};
